# Site settings
title: AnnaKim's Blog
description: Hello World!
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: https://annajinee.github.io/" 
# the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Anna Kim
user_description: Full Stack Developer, Spring boot / Django / RESTful API / Angular2
user_title: Software Developer
email: annajinee@gmail.com
twitter_username: lorem_ipsum
github_username:  annajinee
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
